# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-31 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.CharField(max_length=32, verbose_name='磁盘容量GB'),
        ),
    ]
